{% set name = "aiomcache" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3efd96b646a08cc2bb9af1066caff8a122e54a5af1db81a98f3d80be3a0972d8

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.4.0
  run:
    - python >=3.4.0

test:
  imports:
    - aiomcache

about:
  home: https://github.com/aio-libs/aiomcache/
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Minimal pure python memcached client

extra:
  recipe-maintainers:
    - epruesse
